@startuml
'https://plantuml.com/class-diagram

interface SqlSessionFactory
class DefaultSqlSessionFactory
class SqlSessionManager

SqlSessionFactory <|-- DefaultSqlSessionFactory
SqlSessionFactory <|-- SqlSessionManager

@enduml